# Generated by Django 4.2.7 on 2023-12-03 19:12

from django.db import migrations


def create_static_moments(apps, schema_editor):
    TimelineEvent = apps.get_model("core", "TimelineEvent")
    User = apps.get_model("auth", "User")

    user = User.objects.first() or User.objects.create(username="staticuser")

    static_moments = [
        {
            "user": user,
            "text_content": "I finally did it. After 6 years, I'm officially a med grad!",
            "image_content": "moments_images/gradday.jpg",
        },
        {
            "user": user,
            "text_content": "Bought my first house at 26",
            "image_content": "moments_images/cotsworld2.jpg",
        },
        {
            "user": user,
            "text_content": "Conquered my fear of heights today at the O2 Arena",
            "image_content": "moments_images/o2_arena.jpg",
        },
    ]

    for moment in static_moments:
        TimelineEvent.objects.create(**moment)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_post_author_remove_post_image_and_more"),
    ]

    operations = [
        migrations.RunPython(create_static_moments),
    ]
