# Generated by Django 4.2.7 on 2023-12-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231203_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='image_content',
            field=models.ImageField(blank=True, upload_to='moments_images/'),
        ),
    ]
