# Generated by Django 4.2.7 on 2023-12-04 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_remove_comment_post_comment_timeline_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
